def tum_metinler_tr():
    m1="Mevcut Versiyon:"
    m2="Mevcut versiyon okunamadı:"
    m3="HATA: Downloader dosyası bulunamadı "
    m4="Güncel Versiyon"
    m5="Güncel versiyon bilgisi alınamadı: "
    m6="⬇️  Güncelleme indiriliyor..."
    m7="❌ HATA: Zip dosyası indirilemedi!"
    m8="📦 Dosyalar ayıklanıyor ve taşınıyor..."
    m9=" -> Assets.zip güncellendi."
    m10=" -> HytaleServer.jar güncellendi."
    m11=" -> HytaleServer.oat güncellendi."
    m12="✅ Güncelleme başarıyla tamamlandı!"
    m13="❌ Dosya taşıma sırasında hata: "
    m14="🔍 Güncellemeler kontrol ediliyor..."
    m15="Versiyonlar Getirildi"
    m16="⚠️  Mevcut versiyon okunamadı, sunucu yine de başlatılacak."
    m17="⚠️  Sunucuya bağlanılamadı, güncelleme kontrolü atlanıyor."
    m18="   ℹ️  Mevcut: "
    m19="   ℹ️  Güncel: "
    m20="Karşılaştırılıyor"
    m21="✨ YENİ VERSİYON BULUNDU! Güncelleme başlatılıyor..."
    m22="✅ Sunucu güncel."
    m23="🤖 [OTOMATİK]: "
    m24="Komut gönderilemedi: "
    m25="⏱️ Zamanlayıcı: "
    m25r=" saat sonra restart atılacak."
    m26="DIKKAT: Sunucu "
    m26r=" dakika icinde yeniden baslatilacak!"
    m27="Sunucu yeniden baslatiliyor..."
    m28="Güncelleme Kontrol Ediliyor."
    m29="🚀 Sunucu Başlatılıyor: "
    m30="HATA: Java veya Jar bulunamadı!"
    m31="🛡️ Hytale Sunucu Yöneticisi ve Güncelleyici Aktif."
    m32="Başlatma Komutu: "
    m33="Uyarı Dakikaları Tipi: "
    m34="Güncelleme Yolu:"
    m35="🛑 Script durduruldu."
    m36="⚠️ Sunucu kapandı (Kod: "
    m37=" "
    m37r="Saniye bekleyip tekrar açılacak..."
    m38="🛑 Çıkış yapılıyor."
    return [m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,m15,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25,m25r,m26,m26r,m27,m28,m29,m30,m31,m32,m33,m34,m35,m36,m37,m37r,m38]
def tum_metinler_en():
    m1="Current Version:"
    m2="Current version could not be read:"
    m3="ERROR: Downloader file not found"
    m4="Latest Version"
    m5="Latest version information not available:"
    m6="⬇️  Downloading update..."
    m7="❌ ERROR: Zip file could not be downloaded!"
    m8="📦 Files are being extracted and moved..."
    m9=" -> Assets.zip updated."
    m10=" -> HytaleServer.jar updated."
    m11=" -> HytaleServer.oat updated."
    m12="✅ Update successfully completed!"
    m13="❌ Error during file transfer: "
    m14="🔍 Checking for updates..."
    m15="Versions Retrieved"
    m16="⚠️  Current version could not be read, server will still start."
    m17="⚠️  Could not connect to server, skipping update check."
    m18="   ℹ️  Current: "
    m19="   ℹ️  Latest: "
    m20="Comparing"
    m21="✨ NEW VERSION FOUND! Update starting..."
    m22="✅ Server is up to date."
    m23="🤖 [AUTOMATIC]: "
    m24="Command failed: "
    m25="⏱️ Timer: "
    m25r=" hour until restart."
    m26="ATTENTION: Server will restart in "
    m26r=" minutes!"
    m27="Server restarting..."
    m28="Checking for updates."
    m29="🚀 Server Starting: "
    m30="ERROR: Java or Jar not found!"
    m31="🛡️ Hytale Server Manager and Updater Active."
    m32="Start Command: "
    m33="Warning Minutes Type: "
    m34="Update Path:"
    m35="🛑 Script stopped."
    m36="⚠️ Server shut down (Code: "
    m37=" Will wait "
    m37r="  seconds and restart..."
    m38="🛑 Logging out."
    return [m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,m15,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25,m25r,m26,m26r,m27,m28,m29,m30,m31,m32,m33,m34,m35,m36,m37,m37r,m38]
def metinleri_yukle(dil):
    if dil == "TR":
        return tum_metinler_tr()
    elif dil == "EN":
        return tum_metinler_en()
    else:
        print(f"⚠️ Uyarı: Desteklenmeyen dil '{dil}'! Varsayılan olarak Türkçe (TR) kullanılacak.")
        print(f"Supported languages: TR, EN. Unsupported language '{dil}'! Defaulting to Turkish (TR).")
        return tum_metinler_tr()